"""Add completed columns to Footprint

Revision ID: 5c2d8b0b72ba
Revises: 8b4ed4105144
Create Date: 2025-09-02 06:46:06.636516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2d8b0b72ba'
down_revision: Union[str, Sequence[str], None] = '8b4ed4105144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
